### ISSUE TITLE
Provide a seperate config File

### ISSUE THREAD

**Issue by bratkartoffel** [monstaftp/Monsta-FTP#10]
Hi,

after upgrading Monsta to a new version all customized settings are lost.

Other applications solve this issue like this:
a) Include a "config.inc.php" with the default values
b) Check for existance of an "user_config.inc.php" and include if present

Please provide some system to store the configuration in an extra file which is not included in the distribution. This helps to automate software updates and is less error prone when you oversee some setting after upgrading.

Regards,
Simon

**Comment by monstaftp** [comment]
Resolved in current version
