### ISSUE TITLE
Version 1.5.1+ redirects to non-secure URL

### ISSUE THREAD

**Issue by megadr01d** [monstaftp/Monsta-FTP#15]
This is strange but since v1.5.1, when accessing Monsta FTP's dir, the URL always defaults to `http://`, even if I enter `https://` by hand. Can anyone else confirm this?

[EDIT] I just remembered that the version check introduced in v1.5, I think, uses an `iframe` and gets the info from a non-secure URL, `http://www.monstaftp.com/vc.php`.

[EDIT2] My suspicion was right, setting `$versionCheck = 0;` honours the default protocol and doesn't redirect. This must be fixed so passwords are not sent in clear text.

**Comment by greecemunky** [comment]
@monstaftp Thanks again for the prompt merge.

**Comment by greecemunky** [comment]
@monstaftp Thanks again for the prompt merge.
@megadr01d Try with the latest master.

**Comment by greecemunky** [comment]
@monstaftp Are there any plans to have HTTP and HTTPS version checking, so it's handled by the same protocol?

**Comment by monstaftp** [comment]
Yes this was a definite oversight when we included the iframe. Lately I have seen includes using just // instead of http(s):// to cover both secure and non. Not sure if this would work?

**Comment by greecemunky** [comment]
I think **//** honours the connecting protocol, so if I had Monsta FTP hosted on https://www.myfakedomain.com an IFRAME src of //www.monstaftp.com/vc.php will stay on HTTPS therefore the URL used would be https://www.monstaftp.com/vc.php.  That won't work either as SSL isn't properly set up.  When SSL is set up for www.monstaftp.com, //www.monstaftp.com/vc.php can be used for the IFRAME.

**Comment by monstaftp** [comment]
As of v1.6 the frame loads from an https URL.
