### ISSUE TITLE
Please help! Can't see any files in FileExplorer although the ftp connection is established and files can be uploaded

### ISSUE THREAD

**Issue by JeffCorract** [monstaftp/Monsta-FTP#20]
Hallo,
I've following problem:
I'm using MonstaFTP v1.5.3 on my Apache server. I can connect to my FTP and also upload files. But I cannot see any file or folder of the ftp, neither the just uploaded files. 
![01](https://cloud.githubusercontent.com/assets/12594089/7795225/1a94ddd4-02d3-11e5-8c3d-9c0f125b8519.jpg)
Debugging the PHP site, following errors are shown:
![02](https://cloud.githubusercontent.com/assets/12594089/7795231/350fe6b8-02d3-11e5-8caa-fd01668c9393.jpg)
![03](https://cloud.githubusercontent.com/assets/12594089/7795233/3734bad6-02d3-11e5-9611-60ca12c1409e.jpg)
Does anybody know this issues or can help to solve it?
Thanks for your support!

**Comment by greecemunky** [comment]
Which web browser/s have you tried?  Have you tried others?

**Comment by JeffCorract** [comment]
Normally i'm using Safari but I've also tried with Chrome.

**Comment by greecemunky** [comment]
Not sure what would be causing this to occur.  Can you temporarily log FTP traffic between Apache and the FTP server?  If the FTP server is running Linux, you may be able to install and use package tcpflow to record an FTP conversation and see what commands and responses are taking place behind the scenes (alternatively, there's tcpdump, but a lot more detail is captured so it could make sifting through its output tedious).  If it's a Windows FTP server, you could use Wireshark to capture packets on TCP port 21 and use a display filter (ftp) to see just the FTP conversation.

If the FTP conversation looks okay (i.e. no errors to FTP commands executed), then it could be a browser rendering issue, but not as likely if it's occurring across multiple browsers and to my knowledge no-one is experiencing the same problem.  View the HTML source code and see if the any/all files in the current folder, that should be visible, are referenced in the source code.

**Comment by JeffCorract** [comment]
I’ve tried many things now and I still haven’t found the error. Here my observations:
I’m able to connect to my FTP server all over the web (e.g. via www.2ftp.de, a online ftp tool), see all files and mange them
I’m also able to connect via MonstaFTP on my Apache to every FTP Server in the web:
![ohne titel](https://cloud.githubusercontent.com/assets/12594089/8168757/7c2aea7e-13a5-11e5-91c5-e753a0005a12.jpg)
But if try to connect with MonstaFTP (on my Server via Apache) to my FTP server (also on this server) it doesn’t work.
I do not understand the correlation. Perhaps there is a firewall problem but i’ve also tried to run the server in a „exposed host“ mode without any improvement.
Any ideas what this error is based on?

**Comment by greecemunky** [comment]
What operating system and FTP server software are you running?  It could be that Monsta FTP cannot safely interpret the output from the LIST command (or equivalent) that Monsta FTP is executing, or the executed command is failing.

If you can run tcpflow on Linux, you can have the conversation play out to the console while attempting to log in via your Monsta FTP install, e.g. `tcpflow -Ce 'tcp port 21'`

**Comment by JeffCorract** [comment]
I'm running Mac OS 10.9.5 Server with the integrated FTP Server.
I'll try to test tcpflow and check the connection.

**Comment by greecemunky** [comment]
I just remembered the file listing usually comes down the FTP data channel, so you will most likely need a different tcpflow command.  I've tested the following locally:

`tcpflow -Ce -i any 'tcp and (src and dst host SERVER_IP) and not port 22 and not port 80 and not port 443'`

Replace **SERVER_IP** with your server's IP address.

The command above listens to all TCP traffic excluding SSH, HTTP and HTTPS.  On Linux, listening on the default eth0 adapter did not capture packets (they were caught on lo), hence the addition of `-i any`.  Not sure if this is required for Mac OS X, or if `-i any` will be accepted.

The command is also best run with no other local FTP sessions active at the time to minimise external interference.

**Comment by greecemunky** [comment]
The issue could be with the OS/platform detection by Monsta FTP, found in function **getPlatform()**.  Instead of using the FTP command SYST to determine the platform, it appears to run a LIST command on the root folder and use its own logic to determine if it's a Linux or Windows server.  If the returned data doesn't match either logic (which Mac OS X's server may not), it may fail to set session variable **$_SESSION["win_lin"]** with a usable value, which gets used elsewhere to generate arrays for displaying content.

Can you paste the output from the first LIST command?  I've included output from one of my Linux servers.

`LIST .`
`150 Here comes the directory listing.`
`drwxr-xr-x   56 ftp      ftp          4096 Jun 17 00:18 ftp`
`226 Directory send OK.`

**Comment by JeffCorract** [comment]
Thanks for your infos, I'll try it as soon as possible.

**Comment by monstaftp** [comment]
Just checking one thing... does the server MonstaFTP is installed on allow outbound FTP connections?

**Comment by JeffCorract** [comment]
@monstaftp: I think so, otherwise i couldn't login on other FTP servers from monstaFTP and couldn't connect to my FTP server via web services like 2ftp.de.
Or am I wrong?

**Comment by greecemunky** [comment]
Do you have, or can you create, a test FTP account on your server with dummy files that can be used for testing?

**Comment by JeffCorract** [comment]
Here data for a test account:
iizone.de
Login: test
Password: test

**Comment by greecemunky** [comment]
I performed a test and I see the following:

`LIST .`
`150 Opening ASCII mode data connection for '/bin/ls'.`
`total 14`
`-rw-r--r--  1 test  staff     6148 Jun 28 12:08 .DS_Store`
`-rw-r--r--  1 test  staff  7110327 Mar 27 18:45 [FILENAME].m4a`
`226 Transfer complete.`

It is failing to detect the OS type due to not knowing (not expecting) data like **total 14** on the first line.  A workaround for Mac OS X is needed (I can try working on something but it may not be available for a couple of days).

**Comment by JeffCorract** [comment]
Thank you very much for your support.
I've waited so long to make it work, a view days more or less are no problem :)

**Comment by greecemunky** [comment]
The proposed changes are a bit of a hack - adjusting or copying calls to the Linux "win_lin" value.  Initial tests on your FTP server show it's working (file listing, upload file and deletion of uploaded file).

**Comment by greecemunky** [comment]
@monstaftp Thanks for the prompt merge.
@JeffCorract Either download the latest index.php file and overwrite your one; or, download the latest master ZIP, backup your current Monsta FTP config.php file, overwrite your current Monsta FTP install (excluding config.php!) and test. Close this ticket if it works as expected.

**Comment by JeffCorract** [comment]
Thanks for your help, it works fine now!
