### ISSUE TITLE
Allow setting a default username and password in config.php

### ISSUE THREAD

**Issue by soham2008xyz** [monstaftp/Monsta-FTP#24]
A default username and password could be useful for auto-login in some scenarios.

**Comment by greecemunky** [comment]
Is your suggestion for these to be pre-filled values, where the user only needs to press the login button (or can change the values before pressing the login button)?  Or would you prefer them be hard-coded so the end user cannot change them (like variable $ftpHost) ?

Unless secured via other measures, or disconnected from the Internet entirely, it will be open to abuse.

**Comment by monstaftp** [comment]
Yes, I wouldn't recommend this at all.
