### ISSUE TITLE
Help wanted! Direct login without login screenj

### ISSUE THREAD

**Issue by JeffCorract** [monstaftp/Monsta-FTP#31]
I want MonstaFtp to directly log in a ftp server without getting to the login screen. Unfortunatelly I do not find the code part to manipulate. Has anyone done this before and can provide me his index.php?
Thanks a lot

**Comment by greecemunky** [comment]
If I was to try this, I would edit function **attemptLogin()**, performing an initial test to make sure your hardcoded credentials checked out (via a test login), and if that succeeded, store them in to the applicable $_SESSION variables and perform a real connect via Monsta FTP's **connectFTP()** function.

An example, briefly tested:
delete the 3 lines starting with "} else {" and ending with "if ($_POST["login"] == 1) {", then replace with the following:

    } else {

        $override_username = "ftp.username";
        $override_password = "ftp.password";
        $override_host = "ftp.host.name";
        $override_port = "21";
        $override_ssl = 0;  // 0 or 1
        $tmpftp = ($override_ssl ? @ftp_ssl_connect($override_host, $override_port) : @ftp_connect($override_host, $override_port));
        if (is_resource($tmpftp))  {
            if (@ftp_login($tmpftp,$override_username,$override_password))  {
                $_SESSION["ftp_host"] = trim($override_host);
                $_SESSION["ftp_port"] = trim($override_port);
                $_SESSION["ftp_pasv"] = 1;  // 0 or 1
                $_SESSION["ftp_ssl"]  = $override_ifssl;  // 0 or 1
                $_SESSION["ftp_user"]  = trim($override_username);
                $_SESSION["ftp_pass"]  = trim($override_password);
                $_SESSION["interface"] = "bas";  // adv or bas
                $_SESSION["skin"]      = "monsta";  // your choice
                $_SESSION["lang"]      = "en_us";  // your choice
                $_SESSION["ip_check"]  = 1;  // 0 or 1
            }
        }
        if (connectFTP(0) == 1) {
            
            $_SESSION["loggedin"] = 1;
            
            // Save user's IP address
            $_SESSION["user_ip"] = $_SERVER['REMOTE_ADDR'];
            
            // Set platform
            getPlatform();
            
            // Change dir if one set
            if ($ftpDir != "") {
                if (@ftp_chdir($conn_id, $ftpDir)) {
                    $_SESSION["dir_current"] = $ftpDir;
                } else {
                    if (@ftp_chdir($conn_id, "~" . $ftpDir))
                        $_SESSION["dir_current"] = "~" . $ftpDir;
                }
            }
        }
        elseif ($_POST["login"] == 1) {

Replace the values in variables $override_* and some of the $_SESSION variables as necessary.

**Comment by JeffCorract** [comment]
Thanks for that grateful help. It works pretty nice now
