### ISSUE TITLE
Zip or rar files downloaded by Monsta fiction corrupted V 1.5.3

### ISSUE THREAD

**Issue by danieellz** [monstaftp/Monsta-FTP#45]
Problem when file download (zip or rar), uploading it works and if I download another ftp, it opens normal but if I download monsta ftp, whether the file (zip or rar). he accuses this corrupted and will not open.
Monsta'm using FTP v. 1.5.3
help me please

**Comment by fufomonsta** [comment]
I have same problems, the upload works but de download with any file he accuses corrupted file.
I have upload empty zip, and download it, then open and compare two zip files. I see difference in the notepad:
Original:"PK  "
Current:"   PK  "
![issue](https://cloud.githubusercontent.com/assets/13981989/9494583/105171ea-4bdd-11e5-95c9-05ea6fb5ef3c.png)

**Comment by fufomonsta** [comment]
My english it´s bad, i Know. Sorry for this.

**Comment by Biflette** [comment]
I found the solution. 

For a reason that i ignore, you cannot use an other language than ENGLISH. If u use another, all files will be corrupted when downloading from MONSTA.

So i forced english on my monsta, and it's fine. But definately an issue with translation code !

**Comment by monstaftp** [comment]
This has been resolved in v1.6.

**Comment by fufomonsta** [comment]
thank you very much, I could fix error with you help. (translation)
But now I have a new issue, hahaha. (i helper adicted).
I correctly download the archive (rar, jpg, zip, and so on), but the download begins as the multipart download. When start second part, the download stop and start form the beginning again as a singlepart archive.
I cant find error. I search in the php.ini httpd.conf and index.php in the monsta but i dont see the diference.
![download1](https://cloud.githubusercontent.com/assets/13981989/9518812/57185c48-4c90-11e5-90ae-50e69f0d5ba0.png)
![download2](https://cloud.githubusercontent.com/assets/13981989/9518815/57894386-4c90-11e5-845a-27b93dc867d2.png)
![download3](https://cloud.githubusercontent.com/assets/13981989/9518813/5722825e-4c90-11e5-9ae0-2f457aaa44ea.png)

**Comment by fufomonsta** [comment]
I know my English is poor, I apologize for that.
I am grateful to know that there are people that can answer my questions and help.

I am a curious person, who has a lot of ambition of knowledge but do not have the means to be in a college or university learning.
Thanks to the internet , I learned English (a little haha) , and programming languages ​​like html , php , java . And I've discovered that when a build a page or program I meets the child I once was , which only knows there is a world to learn and that you just have to be encouraged to find out. It is build to play , puzzles , buildings, imaginary worlds , etc. Discovering that we are a small part of a universe, no matter the size of material things but the size of our thoughts.
Thank you for your help.

My english is too bad, for this reason i will transcribe the original text in spanish.

(Se que mi ingles es pobre, pido disculpas por ello
Estoy muy agradecido de saber que hay gente en la cual puedo resolver mis dudas y recibir ayuda.
Soy una persona curiosa, que tiene mucha ambición de conocimiento pero que no posee los medios para estar en una institución o universidad aprendiendo.
Gracias a internet, he aprendido inglés (un poco jaja), y lenguajes de programación como html, php, java. Y he descubierto que cuando uno construye una página o programa, se encuentra con ese niño que una vez fue, que solo sabe que hay un mundo entero por aprender y que solo hay que animarse a descubrirlo. Es jugar a construir, rompecabezas, edificios, mundos imaginarios, etc. Aprender que somos una pequeña parte de un universo, pero que no importa el tamaño físico de las cosas sino la magnitud de nuestros pensamientos. 
Gracias por su ayuda.)

**Comment by Biflette** [comment]
Which FTP server are you using ? Are you using Windows, or *nix server?

Then check log's ftp, who will probably give u some informations about the problem.

Did u checked with an other client ? ( i mean are you alone to have this kind of problem?)
