### ISSUE TITLE
Unzip function ?

### ISSUE THREAD

**Issue by BenasPaulikas** [monstaftp/Monsta-FTP#47]
Any plans for it ?

**Comment by monstaftp** [comment]
Unzip will be available in the next version (2.0) probably as an add-on.

**Comment by ggeorgg** [comment]
When will you launch version 2.0 ? I am very interested in this feature ;)

**Comment by monstahq** [comment]
Version 2 is currently in development. It will be launching before June.

**Comment by ggeorgg** [comment]
Great news!
Thanks a lot.
