### ISSUE TITLE
Files beginning with blank space problem

### ISSUE THREAD

**Issue by OscarAkaElvis** [monstaftp/Monsta-FTP#48]
I think i encountered a bug. If a file exists on ftp (not uploaded with monsta) that its name begins with a blank space, an error ocurrs if you try to download that file with monsta.

Cheers

**Comment by monstaftp** [comment]
I've tried to resolve this but I'm unsure where to next. I've posted the problem to StackOverflow (http://stackoverflow.com/questions/32364883/how-to-handle-spaces-with-preg-split-in-php) but am yet to receive a reply. It's to do with how preg_split handles spaces, which is failing.

**Comment by OscarAkaElvis** [comment]
I saw the post on stackoverflow. Not sure about you want to do... maybe try a simple trim:

$ff = preg_split("/[\s]+/", trim($ff), 9);

If is not useful to you, put an example of entire $raw_string please!

**Comment by OscarAkaElvis** [comment]
Ohhh is see... the blank space as a part of the name is "deleted" by preg_split... let me explore about options. Forget my last post.

**Comment by OscarAkaElvis** [comment]
Try this: remove the + symbol from the regexp:
$ff = preg_split("/[\s]/", $ff, 9);

**Comment by monstaftp** [comment]
Thanks for the suggestion, but that doesn't resolve the problem. It just
adds date/user strings to the beginning of the file name.

**Comment by OscarAkaElvis** [comment]
Please, provide an entire example of $ftp_rawlist.

**Comment by greecemunky** [comment]
In place of:

    $ff = preg_split("/[\s]+/",$ff,9);

Replace with:

    preg_match('/'. str_repeat('([^\s]+)\s+', 7) .'([^\s]+) (.*)/', $ff, $matches);
    $ff = array_slice($matches, 1);

Source:  http://php.net/manual/en/function.ftp-rawlist.php#69551

URL is preserved, however visually it appears to have been stripped.  I've not looked to see where that's taking place, but your files with a space can be downloaded.

**Comment by monstaftp** [comment]
Can you explain the change from number 9 to number 7? I can't quite remember what the significance of the number is. On Windows, the number is 4, so I'm not sure if this would change if replacing the code.

**Comment by greecemunky** [comment]
Sorry, I didn't see this until now.

It repeats **([^\s]+)\s+** 7 times (matches 1 through 7), the 8th match is **([^\s]+)** and the 9th is **(.*)**.  It is the same as doing it like:

    preg_match('/([^\s]+)\s+([^\s]+)\s+([^\s]+)\s+([^\s]+)\s+([^\s]+)\s+([^\s]+)\s+([^\s]+)\s+([^\s]+) (.*)/', $ff, $matches);

The important bit is **([^\s]+) (.*)**.  Between the 8th and 9th character sets, it only allows one space to be used as a separator, and any additional spaces are considered part of the 9th match.

**(.*)** could be changed to **(.+)**, as the former can still match if there's 0 characters, the filename variable effectively being an empty string.  The latter says there must be at least one character for the filename.

It shouldn't affect Windows as I don't think neither NTFS or FAT file systems allow for filenames beginning or ending in a space.

**Comment by greecemunky** [comment]
I am in the middle of creating a fix for this, but I still need to test it.  I also suggest renaming the current sanitize function to something like sanitizeStrTrim, and change all existing calls to it.  A new function sanitizeStr will be used to sanitize but not trim strings, which may required for this to properly show.

**Comment by monstaftp** [comment]
Yes that is a good idea. If you want to add the code for this I'll merge the pull.

**Comment by monstaftp** [comment]
This has been resolved as of v1.6.4.
