### ISSUE TITLE
ZipArchive file may contain unexpected files

### ISSUE THREAD

**Issue by greecemunky** [monstaftp/Monsta-FTP#49]
When a temporary ZIP file is produced but not deleted e.g. if cancelled by the user during the download phase, the temp ZIP file remains on the web server.  Because the file name is static, the same file is referenced the next time the Download function is called by any user.  This could result in the next user ending up with files from the last.

Fix - change file name convention, as suggested in #37.  Example:

From:

```
        $zip_file = $serverTmp."/"."monstaftp_zip_download.zip";
```

To:

```
        $zip_file = tempnam($serverTmp, "monsta-") . ".zip";
```

Additionally, because files may remain on the server due to incomplete transfers, some housecleaning should be performed on folder $serverTmp, deleting files beginning with "$serverTmp/monsta-" over a certain age e.g. 2 days old.  This can be added to index.php in a function that's not called too often e.g. fresh logins, and optionally suggested as a cron job.

**Comment by monstaftp** [comment]
At the time of coding I was wondering if this consistent file name was a good idea. Perhaps a better alternative to save cleaning up /tmp is "monstaftp_YYYY_MM_DD_HH_MM_SS.zip"

**Comment by greecemunky** [comment]
I think that naming convention is appropriate for output files (used in the HTTP headers) however for the web server's temp directory I would still recommend a completely random filename.  Although extremely rare, there could be an instance where two users click the Download button in the same second, resulting in identical filenames therefore affected by this issue.

My suggestion, including yours, for the server's temp file:

    $zip_file = tempnam($serverTmp, "monstaftp_".date("Y_m_d_H_i_s")."-") . ".zip";

I think there was a reverted commit that leveraged PHP's register_shutdown_function() function to erase the  generated file.  If it worked as expected, that may be all that's required to prevent the web server's temp directory from filling when reintroduced.

**Comment by monstaftp** [comment]
I've implemented the change as suggested. It does bring up the wider question of whether all files being delivered to /tmp should be handled this way.
