### ISSUE TITLE
PSR-2 Everything

### ISSUE THREAD

**Issue by joe-meyer** [monstaftp/Monsta-FTP#5]
First off I only recently stumbled across this little gem of a project and find it very promising. 

I think to achieve consistency when having other developers contribute it would be best to adopt the [psr-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) standard for all of the php code. With there being many auto formatters out there and most IDE's already having this functionality built in I think that it could be a relatively painless change that helps with consistency going forward.

**Comment by monstaftp** [comment]
Thanks Joe. I have implemented this for v1.4.12.
