### ISSUE TITLE
Many changes (inadvertently?) reverted

### ISSUE THREAD

**Issue by greecemunky** [monstaftp/Monsta-FTP#50]
It appears commit https://github.com/monstaftp/Monsta-FTP/commit/f262af9928a383b09c44fd6342adb1964ae478a9 has reverted a lot of work previously committed.

I've only had a brief look, but from what I can tell the last pull request that is still present in the master is #23.

**Comment by monstaftp** [comment]
Yes, regrettably we had to roll back some of the pulls for the latest version due to improper testing of commits. We did send out a note about this to our mailing list and invited contributors to resubmit changes. From now on we'll more thoroughly test pull requests before committing. There were issues with some of the previous commits.

**Comment by greecemunky** [comment]
Thanks for that, I wasn't aware.  I'll go through my changes (and possibly others', if they don't mind) and resubmit.

Do you know with approximately which commit things went wrong?

**Comment by monstaftp** [comment]
It was probably the last one where a user added in the ability to include a header. That stuffed up the display of the login screen and I couldn't easily fix it.

**Comment by greecemunky** [comment]
Would it be possible to revert to the commit prior to the problematic merge, possibly https://github.com/monstaftp/Monsta-FTP/commit/1b6b92f3184776f570491e4e1ea2ead8c0cefdd6#diff-828e0013b8f3bc1bb22b4f57172b019d, and manually replay your last commit?

I can try to do it myself, but not sure when I'll get time to.

**Comment by monstaftp** [comment]
It would be great if you could re-add your changes :-) I'm afraid my subsequent edits for the most recent versions are so widespread as to make merging a big task. It's regretful I had to revert to the prior version.
