### ISSUE TITLE
Separate Instructions / Documentation from source code

### ISSUE THREAD

**Issue by EC-Joe** [monstaftp/Monsta-FTP#6]
While the package currently is bundled into a couple neat and tiny files there are some things which I think should be separated out for the sake code readability.

1. Configuration items are over documented in the source code. It should be somewhat obvious what their purpose is by their variable names, and configuration documentation should be created or added to the readme.md
2. The license is included in the index.php file but also in the LICENSE file, this is redundant and not needed noise.
3. The flower boxes to indicate the separate  sections of the code should probably go. Again it should be obvious based on their location, function names, etc what their purpose is

**Comment by monstaftp** [comment]
Thanks Joe. I have implemented this for v1.4.12.
