### ISSUE TITLE
Some sizes don't show up

### ISSUE THREAD

**Issue by megadr01d** [monstaftp/Monsta-FTP#7]
I can't remember about the previous version but since v1.4.12, Monsta FTP fails to retrieve the last modified time for some items. The only way I can make them dsplay is to open the file and re-save it but I can't do that for all files/folders.

![screen shot 2015-02-20 at 00 02 54 am](https://cloud.githubusercontent.com/assets/9649385/6279009/fbb55b34-b893-11e4-8fe1-8373d17a5c76.png)

**Comment by monstaftp** [comment]
Hi Pedro

We fixed an issue where the year was being incorrectly displayed. File
servers only return a year if it's been more than 12 months since the last
update.
If you're able to provide your FTP credentials I'll be happy to diagnose
the error and issue a fix.

Sincerely
Daniel

**Comment by megadr01d** [comment]
Sorry man, I'm on shared hosting, can't go passing credentials like that. Admin won't like it.
Thanks anyway, Daniel.
Do you have links to older versions, say like 1.4.11 and 1.4.10 so I can run a couple of diffs?

**Comment by monstaftp** [comment]
Hi Pedro

Here you go...
http://www.monstaftp.com/download/monsta_ftp_v1.4.12_install.zip

(change version number back as far as 1.4.5)

Cheers
Daniel

**Comment by megadr01d** [comment]
Thanks Daniel, I'll get back to you as soon as I find anything.

**Comment by megadr01d** [comment]
Strange, every version back to 1.4.5 displays the same behaviour. Stranger is that other web file managers/local FTP client display the time correctly.

The pattern I found is that it's not displaying the time for items until 08-2014 (august). From 09-2014 forward, the times display correctly.

**Comment by monstaftp** [comment]
Hi Pedro

I'd be happy to diagnose the problem for you but I'd need you to provide me
FTP access to your install.

Cheers
Daniel

**Comment by megadr01d** [comment]
Daniel, I had to switch to a different domain and therefore reupload my entire website so I can no longer see this issue, for now. Let's close it and I'll check what happens with the times, next year.
