### ISSUE TITLE
Zip files corrupted

### ISSUE THREAD

**Issue by artois33** [monstaftp/Monsta-FTP#8]
Hello,

I'm experiencing an issue while downloading zip files from my server through monsta. They are corrupted when I want to open them.
i have the issue using v1.4.8 and v1.5.

Looks like the ASCII mode is used to download? 

Thanks in advance

**Comment by loctauxphilippe** [comment]
@artois33 I tried, but it's fine for me; check if your zip file is not corrupted

**Comment by greecemunky** [comment]
Same here - no issues.

Make sure PHP's headers haven't already been sent, and other content has not made its way to the zip file that shouldn't have.  Test with a very small zip file - download it, open it in a text editor, and see if there's plain text (i.e. human readable) present in the zip file, toward the beginning and end of the file.

**Comment by danieellz** [comment]
Problem when file download (zip or rar), uploading it works and if I download another ftp, it opens normal but if I download monsta ftp, whether the file (zip or rar). he accuses this corrupted and will not open.
Monsta'm using FTP v. 1.5.3
help me please

**Comment by greecemunky** [comment]
Have you tried with the latest Monsta FTP master file?
Try the suggestions I made, above your comment.
What's your current setup (operating system name and version, web server name and version, PHP version)?

**Comment by danieellz** [comment]
Thank the monsta now worked perfectly
Thank you so ... I downloaded the new version, I think something was missing, but now is perfect

**Comment by danieellz** [comment]
Friend, I just download the latest version of monstaftp, the version I just download right now, is (v.1.5.3), it has not changed anything from the source. just grabbed all the content and I uploaded to my domain, the server hosting platform is an established company here in Brazil Her name is: locaweb and settings that I get in my ports Supported panel is hired (Linux as50-64bits, MySQL 5.6, PostegreSQL 9, ASP.NET 2.0 / 3.5 / 4.0, PHP 5.2 or 5.3) good these were the information contained in my admin panel.

**Comment by greecemunky** [comment]
@danieellz It may be easiest for you to provide temporary test login details (Monsta FTP URL, FTP host, username, password) that has a valid test ZIP file (preferably small in size) already uploaded.

We can also test upload a ZIP file and then re-download it as part of the testing.

**Comment by fufomonsta** [comment]
I have same problems, the upload works but de download with any file he accuses corrupted file.
I have uploaded empty zip, and downloaded it, then open and compare two zip files. I see difference in the notepad:
Original:"PK "
Current:" PK "
![29_3200](https://cloud.githubusercontent.com/assets/13981989/9494652/88f992bc-4bdd-11e5-99a1-c1d8fe04c68e.jpg)
My monsta version is 1.6.
Wamp Server 2.5 - Apache 2.4.9 - Php 5.5.12
host: www.agroingenieria.ddns.net:8080/ftp
User:federico
Pass:fufo

**Comment by loctauxphilippe** [comment]
@fufomonsta what are the sizes of the archives, just to compare them?

**Comment by fufomonsta** [comment]
22 bytes original
22 bytes current

El 26 de agosto de 2015 11:55:52 AM GMT-03:00, Philippe Loctaux <notifications@github.com> escribió:
>@fufomonsta what are the sizes of the archives, just to compare them?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/monstaftp/Monsta-FTP/issues/8#issuecomment-135049370

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by monstaftp** [comment]
I will have a look into your issue. I had believed the issue was fixed in
v1.6.

**Comment by monstaftp** [comment]
There is a line break appearing in the header of your page. I can diagnose
it but I'd need to get access to your install. This will be printing
content to screen before the file downloads which is what will be
corrupting the zip.
